language en_US.UTF-8

set t_Co=256

set encoding=utf8
set fileencoding=utf8
set fileencodings=utf8
set termencoding=utf-8

set autoindent
set smartindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

set list listchars=tab:▸\ ,trail:·,extends:→,precedes:←,nbsp:×

set number
set nowrap
set cursorline nocursorcolumn

set uc=0
set nobackup
set noswapfile
set nowb

set ls=2
set ruler

filetype plugin on

autocmd BufWritePre * :%s/\s\+$//e

set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'git://github.com/scrooloose/nerdtree'
Bundle 'git://github.com/scrooloose/nerdcommenter'
Bundle 'git://github.com/tarmolov/TabLineNumbers.vim'
Bundle 'git://github.com/altercation/vim-colors-solarized.git'
Bundle 'git://github.com/vim-scripts/glsl.vim.git'
Bundle 'git://github.com/vim-scripts/widl.vim.git'
Bundle 'git://github.com/vim-scripts/VimClojure.git'
Bundle 'git://github.com/vim-scripts/opencl.vim.git'
Bundle 'git://github.com/vim-scripts/vim-stylus.git'

au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl
au BufNewFile,BufRead *.idl setf widl
au BufNewFile,BufRead *.cl setf opencl
au BufNewFile,BufRead *.styl setf stylus

syntax on
set background=dark
let g:solarized_termcolors=256
let g:solarized_contrast='high'
colorscheme solarized

" Some TeX-specific settings
au BufRead,BufNewFile *.tex setlocal textwidth=80

" @see http://superuser.com/questions/202848/backspace-key-not-working-in-vim
set bs=indent,eol,start

set langmap=йq,цw,уe,кr,еt,нy,гu,шi,щo,зp,х[,ъ],фa,ыs,вd,аf,пg,рh,оj,лk,дl,ж\\;,э',яz,чx,сc,мv,иb,тn,ьm,б\\,,ю.,ё`,ЙQ,ЦW,УE,КR,ЕT,НY,ГU,ШI,ЩO,ЗP,Х{,Ъ},ФA,ЫS,ВD,АF,ПG,РH,ОJ,ЛK,ДL,Ж:,Э\\",ЯZ,ЧX,СC,МV,ИB,ТN,ЬM,Б<,Ю>,Ё~
