alias la='ls -lA'
alias ll='ls -l'

alias e='vim'

alias vi='vim -n'
alias vir='vim -R'

alias dch='dch --distributor debian'
alias debrelease='debrelease --nomail'

alias grep='grep --color -R --exclude-dir=.git --exclude-dir=.svn'
